name: 'TeaCon 2022 | 焰色反应 | xkball的团队'
on:
  push:
    paths:
      - '.github/workflows/mod-team-flamereaction.yaml'
      - 'mods/team-flamereaction/HEAD'
  workflow_dispatch:
jobs:
  publish:
    name: 'Build 焰色反应'
    environment: Build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Build Environment
        uses: actions/checkout@v2
      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Apply Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys:
            ${{ runner.os }}-gradle-
      # We cannot use action/checkout@v2 because it does not support non-GitHub repositroy.
      # The clone logic used here is adapted from https://stackoverflow.com/a/3489576 for
      # sake of a faster build.
      - name: 'Checkout Repository of Build 焰色反应'
        shell: bash
        run: |
          mkdir -p build/repo
          cd build/repo
          git init
          git remote add origin `cat ../../mods/team-flamereaction/remote`
          git fetch --depth=1 origin `cat ../../mods/team-flamereaction/HEAD`
          git reset --hard `cat ../../mods/team-flamereaction/HEAD`
          git submodule init
          git submodule update
      - name: Validate Gradle Wrapper
        id: gradle_wrapper_check
        continue-on-error: true
        uses: gradle/wrapper-validation-action@v1
        with:
          min-wrapper-count: 1
      - name: Artifact Building
        id: building
        shell: bash
        env:
          GRADLE_WRAPPER_CHECK: ${{ steps.gradle_wrapper_check.outcome == 'success' }}
        run: |
          cd build/repo
          chmod +x ./gradlew
          if [ "$GRADLE_WRAPPER_CHECK" = 'true' ]; then
            ./gradlew -I ../setup.gradle build
          else
            echo '::warning::Gradle wrapper does not seem to exist, this setup is not recommended. Using system-level gradle instead.'
            gradle -I ../setup.gradle build
          fi
      - name: Dedicated Server Launching Test
        id: dedicated_server_launching
        uses: teaconmc/dedicated-launch-test@1.18
        with:
          extra: assemble/extra.json
          mod: ${{ steps.building.outputs.artifact }}
      - name: Extract Mod Description File
        id: description
        shell: bash
        env:
          ARTIFACT_PATH: ${{ steps.building.outputs.artifact }}
        run: cd build && source ../fetch/mods_toml.sh
      - name: Sign
        id: sign
        shell: bash
        env:
          ARTIFACT_NAME: ${{ steps.building.outputs.filename }}
          ARTIFACT_PATH: ${{ steps.building.outputs.artifact }}
          PGP_KEY: ${{ secrets.TEACON_SIGNING_KEY }}
          PGP_PWD: ${{ secrets.TEACON_SIGNING_PWD }}
        run: cd build && source sign.sh
      - name: Publish
        id: publication
        shell: bash
        env:
          TEAM_ID: 'flamereaction'
          ARTIFACT_NAME: ${{ steps.building.outputs.filename }}
          S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_KEY }}
        run: cd build && source publish.sh
      - name: Add Notice
        shell: bash
        env:
          TEAM_ID: 'flamereaction'
          TOKEN: ${{ github.token }}
          ARTIFACT_NAME: ${{ steps.building.outputs.filename }}
          DOWNLOAD_LINK: ${{ steps.publication.outputs.download }}
          MOD_DESCIPTION_BASE64: ${{ steps.description.outputs.base64 }}
        run: cd build && source finish.sh
# Change this counter to trigger all mod rebuild
