name: 'TeaCon 2023 | 傀儡装配(Modular Golems) | Light Land'
on:
  push:
    paths:
      - '.github/workflows/mod-team-modulargolems.yaml'
      - 'mods/team-modulargolems/HEAD'
  workflow_dispatch:
jobs:
  publish:
    name: 'Build 傀儡装配(Modular Golems)'
    environment: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Build Environment
        uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Apply Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys:
            ${{ runner.os }}-gradle-
      # We cannot use action/checkout@v2 because it does not support non-GitHub repositroy.
      # The clone logic used here is adapted from https://stackoverflow.com/a/3489576 for
      # sake of a faster build.
      - name: 'Checkout Repository of Build 傀儡装配(Modular Golems)'
        shell: bash
        run: |
          mkdir -p build/repo
          cd build/repo
          git init
          git remote add origin `cat ../../mods/team-modulargolems/remote`
          git fetch --depth=1 origin `cat ../../mods/team-modulargolems/HEAD`
          git reset --hard `cat ../../mods/team-modulargolems/HEAD`
          git submodule init
          git submodule update
      - name: Validate Gradle Wrapper
        id: gradle_wrapper_check
        continue-on-error: true
        uses: gradle/wrapper-validation-action@v1
        with:
          min-wrapper-count: 1
      - name: Artifact Building
        id: building
        shell: bash
        env:
          BILUOCHUN_URL: https://biluochun.teacon.cn
          TEAM_ID: 170
          GRADLE_WRAPPER_CHECK: ${{ steps.gradle_wrapper_check.outcome == 'success' }}
        run: cd build && ./build.sh
      # We need at least Python 3.11 to ensure existence of tomllib (see PEP 680)
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' 
      - name: Mod Description File Validation
        id: description
        shell: bash
        env:
          TEAM_ID: modulargolems
        run: ./build/mods_toml.py
      - name: Prepare for Dedicated Server Launching Test
        id: dedicated_server_launching_setup
        shell: bash
        run: cd build && ./pre-server-test.sh
      - name: Dedicated Server Launching Test
        id: dedicated_server_launching
        uses: teaconmc/dedicated-launch-test@1.20.1
        with:
          extra: build/main-deps.json
          mod: ${{ steps.building.outputs.artifact }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish
        id: publication
        shell: bash
        env:
          BILUOCHUN_URL: https://biluochun.teacon.cn
          CONTEST_ID: 2023
          TEAM_ID: 'modulargolems'
          TEAM_SEQ: '170'
          BILUOCHUN_TOKEN: ${{ secrets.BILUOCHUN_TOKEN }}
          S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_KEY }}
          # https://github.com/aws/aws-cli/issues/5623
          AWS_EC2_METADATA_DISABLED: 'true'
        run: cd build && ./publish.sh
# Change this counter to trigger all mod rebuild
