name: Scheduled Testing Pack Update
on:
  schedule:
    - cron: "0 1 * * *"
  push:
    paths:
      - 'assemble/blacklist.json'
      - 'assemble/extra.json'
  workflow_dispatch:
concurrency:
  group: pack-update
  cancel-in-progress: true
jobs:
  assemble-mod-list:
    name: Assemble Mod List
    environment: Assemble
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Setup Python3
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'
      - name: Install dependencies
        run: pip3 install boto3
      - name: Assemble Mod List
        env:
          AUTH_TOKEN: ${{ github.token }}
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
          S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET }}
        run: cd assemble && python3 list.py
