name: Scheduled Testing Pack Update
on:
  push:
    paths:
      - 'assemble/blacklist.json'
      - 'assemble/extra.json'
  workflow_run:
    workflows: [ 'TeaCon2021*' ]
    branches: [ 'teacon2021' ]
    types: 
      - completed
  workflow_dispatch:
concurrency:
  group: pack-update
  cancel-in-progress: true
jobs:
  assemble-mod-list:
    name: Assemble Mod List
    environment: Assemble
    runs-on: ubuntu-18.04
    if: ${{ github.event.workflow_run == null || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Setup Python3
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'
      - name: Install dependencies
        run: pip3 install boto3
      - name: Auth as Github App
        id: auth-as-github-app
        shell: bash
        env:
          APP_ID: ${{ secrets.APP_ID }}
          APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
        run: bash auth.sh
      - name: Assemble Mod List
        env:
          AUTH_TOKEN: ${{ github.token }}
        run: cd assemble && python3 list.py
      - name: Copy to teacon/DataPack
        run: |
          source commit_info.sh
          git clone --depth=1 https://github.com/teaconmc/DataPack.git datapack
          cp mod-list.json datapack/2021/mod-list.json
          cd datapack
          git add 2021/mod-list.json
          git commit -m "`date -u`: add 2021 mod list" || true
          git push
