name: PGP Private Key Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: PGP Private Key Test
        env:
          PGP_KEY: ${{ secrets.TEACON_SIGNING_KEY }}
          PGP_PWD: ${{ secrets.TEACON_SIGNING_PWD }}
          GPG_OPTS: --homedir ./.gnupg --batch --pinentry-mode loopback --passphrase-fd 0 --quiet --armor
        run: |
          # write to file
          mkdir -pm 700 ./.gnupg
          cat > teacon.asc <<EOM
          $PGP_KEY
          EOM
          # import the file
          gpg $GPG_OPTS --import teacon.asc <<EOM
          $PGP_PWD
          EOM
          # sign a simple message
          echo TeaCon | gpg --clearsign | tee teacon.sig
          # verify the signature of the message
          gpg --verify teacon.sig
