name: Scheduled Polling
on:
  workflow_dispatch:
jobs:
  fetch-update:
    name: Fetch updates
    environment: Polling
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Setup Python3
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'
      - name: Query updates
        shell: bash
        run: python3 query.py
      - name: Auth as Github App
        shell: bash
        env:
          APP_ID: ${{ secrets.APP_ID }}
          APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
        run: bash auth.sh && bash commit_info.sh
      - name: Commit changes
        shell: bash
        run: |
          git add .github/workflows
          git commit -m "`date -u`: create new build workflow(s)" || true
          git add mods
          git commit -m "`date -u`: trigger new build(s)" || true
          git push
